NopCommerce/Plugins/Nop.Plugin.Tax.Avalara/Models/Checkout/AddressValidationModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.Checkout
{
    /// <summary>
    /// Represents an address validation model
    /// </summary>
    public class AddressValidationModel : BaseNopModel
    {
        #region Properties

        public string Message { get; set; }

        public bool IsError { get; set; }

        public bool IsNewAddress { get; set; }

        public int AddressId { get; set; }

        #endregion
    }
}

NopCommerce/Plugins/Nop.Plugin.Tax.Avalara/Controllers/AddressValidationController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Tax;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Tax.Avalara.Controllers
{
    public class AddressValidationController : BaseController
    {
        #region Fields

        private readonly IAddressService _addressService;
        private readonly ICustomerService _customerService;
        private readonly IWorkContext _workContext;
        private readonly TaxSettings _taxSettings;

        #endregion

        #region Ctor

        public AddressValidationController(IAddressService addressService,
            ICustomerService customerService,
            IWorkContext workContext,
            TaxSettings taxSettings)
        {
            _addressService = addressService;
            _customerService = customerService;
            _workContext = workContext;
            _taxSettings = taxSettings;
        }

        #endregion

        #region Methods

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult UseValidatedAddress(int addressId, bool isNewAddress)
        {
            //try to get an address by the passed identifier
            var address = _addressService.GetAddressById(addressId);
            if (address != null)
            {
                //add address to customer collection if it's a new
                if (isNewAddress)
                    _customerService.InsertCustomerAddress(_workContext.CurrentCustomer, address);

                //and update appropriate customer address
                if (_taxSettings.TaxBasedOn == TaxBasedOn.BillingAddress)
                    _workContext.CurrentCustomer.BillingAddressId = address.Id;
                if (_taxSettings.TaxBasedOn == TaxBasedOn.ShippingAddress)
                    _workContext.CurrentCustomer.ShippingAddressId = address.Id;
                _customerService.UpdateCustomer(_workContext.CurrentCustomer);
            }

            //nothing to return
            return Content(string.Empty);
        }

        #endregion
    }
}

NopCommerce/Plugins/Nop.Plugin.Tax.Avalara/Views/Checkout/AddressValidation.cshtml
@model AddressValidationModel

<script>
    $(document).ready(function () {
        @if (Model.IsError)
        {
            <text>alert('@Model.Message');</text>
        }
        else
        {
            <text>
                var customerConfirmation = confirm('@Model.Message');
                if (customerConfirmation) {
                    var postData = {
                        addressId: '@Model.AddressId',
                        isNewAddress: '@Model.IsNewAddress'
                    };
                    addAntiForgeryToken(postData);

                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "@Url.Action("UseValidatedAddress", "AddressValidation")",
                        data: postData,
                        dataType: "json"
                    });
                }
            </text>
        }
    });
</script>