NopCommerce/Presentation/Nop.Web/Areas/Admin/Controllers/CheckoutAttributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Orders;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class CheckoutAttributeController : BaseAdminController
    {
        #region Fields

        private readonly CurrencySettings _currencySettings;
        private readonly ICheckoutAttributeModelFactory _checkoutAttributeModelFactory;
        private readonly ICheckoutAttributeParser _checkoutAttributeParser;
        private readonly ICheckoutAttributeService _checkoutAttributeService;
        private readonly ICurrencyService _currencyService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IMeasureService _measureService;
        private readonly IPermissionService _permissionService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IStoreService _storeService;
        private readonly MeasureSettings _measureSettings;

        #endregion

        #region Ctor

        public CheckoutAttributeController(CurrencySettings currencySettings,
            ICheckoutAttributeModelFactory checkoutAttributeModelFactory,
            ICheckoutAttributeParser checkoutAttributeParser,
            ICheckoutAttributeService checkoutAttributeService,
            ICurrencyService currencyService,
            ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IMeasureService measureService,
            IPermissionService permissionService,
            IStoreMappingService storeMappingService,
            IStoreService storeService,
            MeasureSettings measureSettings)
        {
            _currencySettings = currencySettings;
            _checkoutAttributeModelFactory = checkoutAttributeModelFactory;
            _checkoutAttributeParser = checkoutAttributeParser;
            _checkoutAttributeService = checkoutAttributeService;
            _currencyService = currencyService;
            _customerActivityService = customerActivityService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _measureService = measureService;
            _permissionService = permissionService;
            _storeMappingService = storeMappingService;
            _storeService = storeService;
            _measureSettings = measureSettings;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateAttributeLocales(CheckoutAttribute checkoutAttribute, CheckoutAttributeModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(checkoutAttribute,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(checkoutAttribute,
                    x => x.TextPrompt,
                    localized.TextPrompt,
                    localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(checkoutAttribute,
                    x => x.DefaultValue,
                    localized.DefaultValue,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdateValueLocales(CheckoutAttributeValue checkoutAttributeValue, CheckoutAttributeValueModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(checkoutAttributeValue,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        protected virtual void SaveStoreMappings(CheckoutAttribute checkoutAttribute, CheckoutAttributeModel model)
        {
            checkoutAttribute.LimitedToStores = model.SelectedStoreIds.Any();
            _checkoutAttributeService.UpdateCheckoutAttribute(checkoutAttribute);

            var existingStoreMappings = _storeMappingService.GetStoreMappings(checkoutAttribute);
            var allStores = _storeService.GetAllStores();
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds.Contains(store.Id))
                {
                    //new store
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        _storeMappingService.InsertStoreMapping(checkoutAttribute, store.Id);
                }
                else
                {
                    //remove store
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        _storeMappingService.DeleteStoreMapping(storeMappingToDelete);
                }
            }
        }

        protected virtual void SaveConditionAttributes(CheckoutAttribute checkoutAttribute, CheckoutAttributeModel model)
        {
            string attributesXml = null;

            if (model.ConditionModel.EnableCondition)
            {
                var attribute = _checkoutAttributeService.GetCheckoutAttributeById(model.ConditionModel.SelectedAttributeId);
                if (attribute != null)
                {
                    switch (attribute.AttributeControlType)
                    {
                        case AttributeControlType.DropdownList:
                        case AttributeControlType.RadioList:
                        case AttributeControlType.ColorSquares:
                        case AttributeControlType.ImageSquares:
                            {
                                var selectedAttribute = model.ConditionModel.ConditionAttributes
                                    .FirstOrDefault(x => x.Id == model.ConditionModel.SelectedAttributeId);
                                var selectedValue = selectedAttribute?.SelectedValueId;

                                //for conditions we should empty values save even when nothing is selected
                                //otherwise "attributesXml" will be empty
                                //hence we won't be able to find a selected attribute
                                attributesXml = _checkoutAttributeParser.AddCheckoutAttribute(null, attribute, string.IsNullOrEmpty(selectedValue) ? string.Empty : selectedValue);
                            }
                            break;
                        case AttributeControlType.Checkboxes:
                            {
                                var selectedAttribute = model.ConditionModel.ConditionAttributes
                                    .FirstOrDefault(x => x.Id == model.ConditionModel.SelectedAttributeId);
                                var selectedValues = selectedAttribute?.Values
                                    .Where(x => x.Selected)
                                    .Select(x => x.Value)
                                    .ToList();

                                if (selectedValues?.Any() ?? false)
                                    foreach (var value in selectedValues)
                                        attributesXml = _checkoutAttributeParser.AddCheckoutAttribute(attributesXml, attribute, value);
                                else
                                    attributesXml = _checkoutAttributeParser.AddCheckoutAttribute(null, attribute, string.Empty);
                            }
                            break;
                        case AttributeControlType.ReadonlyCheckboxes:
                        case AttributeControlType.TextBox:
                        case AttributeControlType.MultilineTextbox:
                        case AttributeControlType.Datepicker:
                        case AttributeControlType.FileUpload:
                        default:
                            //these attribute types are not supported as conditions
                            break;
                    }
                }
            }

            checkoutAttribute.ConditionAttributeXml = attributesXml;
        }

        #endregion

        #region Checkout attributes

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedView();

            //prepare model
            var model = _checkoutAttributeModelFactory.PrepareCheckoutAttributeSearchModel(new CheckoutAttributeSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(CheckoutAttributeSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageAttributes))
                return AccessDeniedDataTablesJson();

            //prepare model

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/Create.cshtml
@model CheckoutAttributeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.CheckoutAttributes.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Checkout attributes");
}

<form asp-controller="CheckoutAttribute" asp-action="Create" method="post" id="checkoutattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Attributes.CheckoutAttributes.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.CheckoutAttributes.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CheckoutAttributeDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/Edit.cshtml
@model CheckoutAttributeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.CheckoutAttributes.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Checkout attributes");
}

<form asp-controller="CheckoutAttribute" asp-action="Edit" method="post" id="checkoutattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Attributes.CheckoutAttributes.EditAttributeDetails") - @Model.Name 
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Attributes.CheckoutAttributes.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="checkoutattribute-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CheckoutAttributeDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="checkoutattribute-delete" />

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/List.cshtml
@model CheckoutAttributeSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.CheckoutAttributes").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Checkout attributes");
}

<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.Catalog.Attributes.CheckoutAttributes")
    </h1>
    <div class="pull-right">
        <a asp-action="Create" class="btn bg-blue">
            <i class="fa fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CheckoutAttributeListButtons })
        <button type="button" id="delete-selected" class="btn bg-red">
            <i class="fa fa-trash-o"></i>
            @T("Admin.Common.Delete.Selected")
        </button>
        <nop-action-confirmation asp-button-id="delete-selected" />
    </div>
</div>

<div class="content">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    @T("Admin.Catalog.Attributes.CheckoutAttributes.Description")
                </p>
                @await Html.PartialAsync("Table", new DataTablesModel
                {
                    Name = "checkoutattributes-grid",
                    UrlRead = new DataUrl("List", "CheckoutAttribute", null),
                    Length = Model.PageSize,
                    LengthMenu = Model.AvailablePageSizes,
                    ColumnCollection = new List<ColumnProperty>
                    {
                        new ColumnProperty(nameof(ProductAttributeModel.Id))
                        {
                            IsMasterCheckBox = true,
                            Render = new RenderCheckBox("checkbox_checkoutattributes"),
                            ClassName =  NopColumnClassDefaults.CenterAll,
                            Width = "50"
                        },
                        new ColumnProperty(nameof(CheckoutAttributeModel.Name))
                        {
                            Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Fields.Name").Text
                        },
                        new ColumnProperty(nameof(CheckoutAttributeModel.AttributeControlTypeName))
                        {
                            Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Fields.AttributeControlType").Text,
                            Width = "200"
                        },
                        new ColumnProperty(nameof(CheckoutAttributeModel.IsRequired))
                        {
                            Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Fields.IsRequired").Text,
                            Width = "100",
                            ClassName = NopColumnClassDefaults.CenterAll,
                            Render = new RenderBoolean()
                        },
                        new ColumnProperty(nameof(CheckoutAttributeModel.DisplayOrder))
                        {
                            Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Fields.DisplayOrder").Text,
                            Width = "100",
                            ClassName = NopColumnClassDefaults.CenterAll
                        },
                        new ColumnProperty(nameof(CheckoutAttributeModel.Id))
                        {
                            Title = T("Admin.Common.Edit").Text,
                            Width = "100",
                            ClassName = NopColumnClassDefaults.Button,
                            Render = new RenderButtonEdit(new DataUrl("Edit"))
                        }
                    }
                })

                <script>
                    $(document).ready(function () {
                        $('#delete-selected-action-confirmation-submit-button').bind('click', function () {
                            var postData = {
                                selectedIds: selectedIds
                            };
                            addAntiForgeryToken(postData);
                            $.ajax({
                                cache: false,
                                type: "POST",
                                url: "@(Url.Action("DeleteSelected", "CheckoutAttribute"))",
                                data: postData,
                                error: function (jqXHR, textStatus, errorThrown) {
                                    $('#deleteSelectedFailed-info').text(errorThrown);
                                    $('#deleteSelectedFailed').click();
                                },
                                complete: function (jqXHR, textStatus) {
                                    updateTable('#checkoutattributes-grid');
                                }
                            });
                            $('#delete-selected-action-confirmation').modal('toggle');
                            return false;
                        });
                    });
                </script>
                <nop-alert asp-alert-id="deleteSelectedFailed" />
            </div>
        </div>
    </div>
</div>

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/ValueCreatePopup.cshtml
@model CheckoutAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.AddNew").Text;
}

<form asp-controller="CheckoutAttribute" asp-action="ValueCreatePopup"
      asp-route-checkoutAttributeId="@Context.Request.Query["checkoutAttributeId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Attributes.CheckoutAttributes.Values.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CheckoutAttributeValueDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateValue", Model)
</form>

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/ValueEditPopup.cshtml
@model CheckoutAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.EditValueDetails").Text;
}

<form asp-controller="CheckoutAttribute" asp-action="ValueEditPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Attributes.CheckoutAttributes.Values.EditValueDetails")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CheckoutAttributeValueDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateValue", Model)
</form>

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/_CreateOrUpdate.Condition.cshtml
@using Nop.Core.Domain.Catalog
@model CheckoutAttributeModel

@if (Model.Id > 0)
{
    <script>
        $(document).ready(function () {
            $("#@Html.IdFor(model => model.ConditionModel.EnableCondition)").click(toggleEnableCondition);
            toggleEnableCondition();
        });

        function toggleEnableCondition() {
            if ($('#@Html.IdFor(model => model.ConditionModel.EnableCondition)').is(':checked')) {
                $('#pnlAttributes').show();
            } else {
                $('#pnlAttributes').hide();
            }
        }
    </script>

    <div class="panel-body">
        <div class="form-group">
            <div class="col-md-3">
                <nop-label asp-for="ConditionModel.EnableCondition" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="ConditionModel.EnableCondition" />
                <span asp-validation-for="ConditionModel.EnableCondition"></span>
            </div>
        </div>
        <nop-nested-setting asp-for="ConditionModel.EnableCondition" id="pnlAttributes">
            @if (Model.ConditionModel.ConditionAttributes.Count > 0)
            {
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="ConditionModel.SelectedAttributeId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="ConditionModel.SelectedAttributeId" asp-items="@(Model.ConditionModel.ConditionAttributes.Select(x => new SelectListItem() {Text = x.Name, Value = x.Id.ToString()}))" />

                        <script>
                            $(document).ready(function() {
                                $("#@Html.IdFor(model => model.ConditionModel.SelectedAttributeId)")
                                    .change(toggleConditionAttributes);

                                toggleConditionAttributes();
                            });

                            function toggleConditionAttributes() {
                                var selectedCheckoutAttributeId =
                                    $("#@Html.IdFor(model => model.ConditionModel.SelectedAttributeId)").val();
                                $('[id^="pnl_attribute_values_"]').hide();
                                $('#pnl_attribute_values_' + selectedCheckoutAttributeId).show();
                            }
                        </script>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">&nbsp;</div>
                    <div class="col-md-9">
                        @for (var i = 0; i < Model.ConditionModel.ConditionAttributes.Count; i++)
                        {
                            <input type="hidden" asp-for="@Model.ConditionModel.ConditionAttributes[i].Id" />
                            <div id="@($"pnl_attribute_values_{Model.ConditionModel.ConditionAttributes[i].Id}")">
                                @switch (Model.ConditionModel.ConditionAttributes[i].AttributeControlType)
                                {
                                    case AttributeControlType.DropdownList:
                                        <nop-select asp-for="@Model.ConditionModel.ConditionAttributes[i].SelectedValueId" asp-items="Model.ConditionModel.ConditionAttributes[i].Values" />
                                        break;
                                    case AttributeControlType.RadioList:
                                    case AttributeControlType.ColorSquares:
                                    case AttributeControlType.ImageSquares:
                                        foreach (var value in Model.ConditionModel.ConditionAttributes[i].Values)
                                        {
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" asp-for="@Model.ConditionModel.ConditionAttributes[i].SelectedValueId" value="@value.Value" checked="@value.Selected" />
                                                    @value.Text
                                                </label>
                                            </div>
                                        }
                                        break;
                                    case AttributeControlType.Checkboxes:
                                        for (var j = 0; j < Model.ConditionModel.ConditionAttributes[i].Values.Count; j++)
                                        {
                                            <div class="checkbox">
                                                <label>
                                                    <input type="hidden" asp-for="@Model.ConditionModel.ConditionAttributes[i].Values[j].Value" />
                                                    <nop-editor asp-for="@Model.ConditionModel.ConditionAttributes[i].Values[j].Selected" />
                                                    @Model.ConditionModel.ConditionAttributes[i].Values[j].Text
                                                </label>
                                            </div>
                                        }
                                        break;
                                    case AttributeControlType.ReadonlyCheckboxes:
                                    case AttributeControlType.TextBox:
                                    case AttributeControlType.MultilineTextbox:
                                    case AttributeControlType.Datepicker:
                                    case AttributeControlType.FileUpload:
                                    default:
                                        //not supported as conditions
                                        break;
                                }
                            </div>
                        }
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        @T("Admin.Catalog.Attributes.CheckoutAttributes.Condition.NoAttributeExists")
                    </div>
                </div>
            }
        </nop-nested-setting>
    </div>
}
else
{
    <div class="panel-body">
        @T("Admin.Catalog.Attributes.CheckoutAttributes.Condition.SaveBeforeEdit")
    </div>
}

NopCommerce/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/_CreateOrUpdate.Values.cshtml
@model CheckoutAttributeModel

@if (Model.Id > 0)
{
    <div class="panel-body">
        @await Html.PartialAsync("Table", new DataTablesModel
        {
            Name = "checkoutattributevalues-grid",
            UrlRead = new DataUrl("ValueList", "CheckoutAttribute", new RouteValueDictionary { [nameof(CheckoutAttributeValueSearchModel.CheckoutAttributeId)] = Model.CheckoutAttributeValueSearchModel.CheckoutAttributeId }),
            UrlDelete = new DataUrl("ValueDelete", "CheckoutAttribute", null),
            Length = Model.CheckoutAttributeValueSearchModel.PageSize,
            LengthMenu = Model.CheckoutAttributeValueSearchModel.AvailablePageSizes,
            ColumnCollection = new List<ColumnProperty>
            {
                new ColumnProperty(nameof(CheckoutAttributeValueModel.Name))
                {
                    Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.Fields.Name").Text
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.PriceAdjustment))
                {
                    Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.Fields.PriceAdjustment").Text,
                    Width = "200"
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.WeightAdjustment))
                {
                    Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.Fields.WeightAdjustment").Text,
                    Width = "200"
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.IsPreSelected))
                {
                    Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.Fields.IsPreSelected").Text,
                    Width = "100",
                    ClassName = NopColumnClassDefaults.CenterAll,
                    Render = new RenderBoolean()
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.DisplayOrder))
                {
                    Title = T("Admin.Catalog.Attributes.CheckoutAttributes.Values.Fields.DisplayOrder").Text,
                    Width = "100",
                    ClassName = NopColumnClassDefaults.CenterAll
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.Id))
                {
                    Title = T("Admin.Common.Edit").Text,
                    Width = "100",
                    ClassName = NopColumnClassDefaults.Button,
                    Render = new RenderCustom("renderColumnEdit")
                },
                new ColumnProperty(nameof(CheckoutAttributeValueModel.Id))
                {
                    Title = T("Admin.Common.Delete").Text,
                    Width = "100",
                    Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                    ClassName = NopColumnClassDefaults.Button
                }
            }
       })
    </div>

    <div class="panel-footer">
        <button type="submit" id="btnAddNewValue"
                onclick="javascript:OpenWindow('@(Url.Action("ValueCreatePopup", "CheckoutAttribute", new { checkoutAttributeId = Model.Id, btnId = "btnRefresh", formId = "checkoutattribute-form" }))', 800, 500, true); return false;"
                class="btn btn-primary">
            @T("Admin.Catalog.Attributes.CheckoutAttributes.Values.AddNew")
        </button>
        <input type="submit" id="btnRefresh" style="display: none" />
        <script>
            $(document).ready(function () {
                $('#btnRefresh').click(function () {
                    //refresh grid
                    updateTable('#checkoutattributevalues-grid');

                    //return false to don't reload a page
                    return false;
                });
            });
        </script>
    </div>
}           
else
{
    <div class="panel-body">
        @T("Admin.Catalog.Attributes.CheckoutAttributes.Values.SaveBeforeEdit")
    </div>
}

<script>
    function renderColumnEdit(data, type, row, meta) {
        return '<button onclick=\"javascript:OpenWindow(\'@Url.Content("~/Admin/CheckoutAttribute/ValueEditPopup/")' + data + '?btnId=btnRefresh&formId=checkoutattribute-form\', 800, 400, true); return false;\" class="btn btn-default"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</button>';
    }
</script>